[정렬] 9월 4일
Altu-Bitu-3/Altu-Bitu-KimYujeong pull request #1
Opened 2022-09-03 16:49 UTC by kimyu0218

#### 내용 & 질문
> 정렬 과제 제출합니다!

#### <기존 제출>
> 문제 번호 1026, 1431, 1758, 1946, 11651

#### <추가 제출>

2022-09-05 06:19 UTC, jaeseo222 reviewed
P3. **11651 코드 리뷰 완료**
안녕하세요 유정님 ☺️☺️ 코드도 너무 깔끔하고 주석도 작성해주셔서 너무 좋았어요!!
간단한 코멘트 달았으니, 확인 부탁드립니다 !

2022-09-05 06:19 UTC, jaeseo222 commented on 09월 02일 - 정렬/11651.cpp
> +vector<pi> cor; // 좌표 정보 저장
p2. **불필요한 전역변수는 지양**하는 것이 좋습니다!! 😄

현재는 코드가 길지 않아 큰 문제가 없지만! 함수 내에서만 사용하는 변수를 전역변수로 선언할 경우, 디버깅이 어려워서 버그를 고치기 어려울 수 있고, 코드가 길어지면 수정하기 어려운 문제가 생기기도 합니다.

물론, 특정 변수를 다양한 함수에서 접근해야 한다면 전역변수로 선언하여 유용하게 사용할 수 있습니다. 🙂

2022-09-05 09:05 UTC, jk0527 requested changes
P2. 1026 코드 리뷰 완료

코드 정말 정말 깔끔하게 잘 짜주셨어요!
minSum을 함수로 뺀 것도 정말 좋은 것 같아요!
전역 변수 부분만 신경 써주시면 더 완벽할 것 같아요!!

2022-09-05 09:05 UTC, jk0527 commented on 09월 02일 - 정렬/1026.cpp
> +vector<int> a, b;
클린 코드를 위해서 전역 변수의 사용을 최대한 지양하고 있습니다!
minSum 함수에서 사용하는 부분은 매개변수로 넘겨주는 형식을 사용하는 것이 어떨까요?

2022-09-05 09:22 UTC, jk0527 approved these changes

2022-09-05 09:53 UTC, kimyu0218 commented
전역변수 모두 지역변수로 수정했습니다! 확인 부탁드립니다.

2022-09-05 09:58 UTC, jk0527 commented
> 전역변수 모두 지역변수로 수정했습니다! 확인 부탁드립니다.

2022-09-07 04:50 UTC, bsa0322 approved these changes
p3. 1758 코드리뷰 완료 
유정님 안녕하세요~! 넘 반갑습니다!!!!!!! 🥰 과제를 항상 일찍 내주셔서 정말 최고예요 ✨ 코드 너무 깔끔하고 좋습니다!! 주석 설명도 잘 써주셔서 너무 좋았어요. 사소한 코멘트 남겼으니 수정해주셔도 좋을 것 같아요! 수고하셨습니다 🥰

\+ 저희가 후에 협업을 할 때를 생각해서 2기 때부터 코드를 작성할 때 중괄호 생략은 지양하고 있어요! 나중에 수정할 일이 생기면, 다시 중괄호를 추가해야할 일이 생길수도 있는데 그렇게 되면 작업이 꼬이거나 충돌이 날 가능성이 있기 때문이죠..!! 하지만 지금은 알고리즘 문제 풀이니까 나중에 수정할 일은 거의 없을테니, 참고만 해주시면 좋을 거 같습니다!

2022-09-07 04:50 UTC, bsa0322 commented on 09월 02일 - 정렬/1758.cpp
> +}
p3. 로직 완전 좋아요!! 그런데 tip에 대해 내림차순 정렬을 진행했었으니, 팁을 주지 않는 경우를 continue 보다 더 완전히 끊어낼 수 있을 것 같네요! cost가 음수인 순간이 나타났다면 그 이후엔 어떨까요?

2022-09-07 11:37 UTC, kimyu0218 commented
1758번 문항 수정했습니다! 확인 부탁드립니다!

2022-09-07 13:38 UTC, bsa0322 commented
> 1758번 문항 수정했습니다! 확인 부탁드립니다!

좋아요!! 수고하셨습니다! 🥰

2022-09-07 16:27 UTC, flowersayo reviewed
1946 코드 리뷰 완료

안녕하세요 유정님  😊 ㅎㅎ
코드를 정말 깔끔하게 잘 작성해주셨어요 완벽합니다..👍 
저희 샘플코드랑 다를게 없어서 제가 더 피드백 드릴 부문이 없네요
바로 머지하셔도 될것 같아요 수고하셨습니다 :)

2022-09-07 16:27 UTC, flowersayo commented on 09월 02일 - 정렬/1946.cpp
> +
맞아요!
본 문제는 서류심사 혹은 면접심사 순위 기준으로 정렬해서 나머지 심사 순위를 비교해가며 푸는 문제였어요. 
그리고 서류 1등은 무조건 뽑히므로 cnt=1 로 초기화해주신 것도 너무 좋아요!

나머지 사람들도 천천히 합격유무를 판단해보면,
서류순위 2등인사람은 서류순위 1등인사람의 면접순위 점수보다 높다면 뽑힐수있어요.
서류순위 3등인사람은 서류순위 1,2 등 인 사람들보다 면접순위점수보다 높다면 뽑힐수 있어요.
서류순위 4등인사람은 서류순위 1,2,3 등 인 사람들보다 면접순위점수보다 높다면 뽑힐수 있죠.
이때 4등을 1,2,3등 각각과 비교하게 되면 O(N2)의 시간복잡도를 가지므로 시간초과가 날꺼에요. 따라서 **가장 높은 면접심사 순위를 계속 갱신해서 O(n)** 으로 풀이해야하는 문제였어요!

2022-09-07 16:27 UTC, flowersayo commented on 09월 02일 - 정렬/1946.cpp
> +typedef pair<int, int> pi;
오 이건 아직 튜터링에서 다루지 않았는데 pair 자료형 사용해주신것도 너무 좋아요👍

2022-09-08 00:49 UTC, jaeseo222 commented
> 전역변수 모두 지역변수로 수정했습니다! 확인 부탁드립니다.

확인 했습니다! 수고 많으셨습니다.☺️☺️

2022-09-08 11:54 UTC, Minseo10 approved these changes
P3: 저희 샘플코드와 거의 똑같아서 사실 고칠 부분이 없는 것 같아요! 사소한 코멘트 남겼으니 참고하시면 좋을 것 같아요 수고하셨습니다 😸

2022-09-08 11:54 UTC, Minseo10 commented on 09월 02일 - 정렬/1431.cpp
> +    }
알파벳인 경우 continue 하고 그외 경우에 숫자를 더하는 방식으로 구현하셨네요!! 샘플코드에서는 isdigit() 함수를 이용하여 숫자인 경우 더하는 방식으로 구현했는데, 이 방법도 직관적이고 아주 좋은 것 같아요😄

2022-09-08 11:54 UTC, Minseo10 commented on 09월 02일 - 정렬/1431.cpp
> +    int sum1 = computeSum(s1), sum2 = computeSum(s2);
굳이 변수 sum1, sum2를 선언하지 않고 바로 computeSum(s1)과 computeSum(s2)를 비교하는게 가독성이 조금 더 괜찮을 것 같아요! 물론 이정돈 취향차이이니 꼭 따르실 필요는 없을 것 같습니다~

2022-09-08 12:10 UTC, merged